package com.jnetai.keyboard.emoji;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class EmojiDatabase {
    public static class EmojiEntry {
        public final String emoji;
        public final String name;
        public final String category;
        public final List<String> keywords;

        EmojiEntry(String emoji, String name, String category, String... keywords) {
            this.emoji = emoji;
            this.name = name;
            this.category = category;
            this.keywords = new ArrayList<>();
            for (String kw : keywords) this.keywords.add(kw.toLowerCase());
        }
    }

    private static final List<EmojiEntry> emojis = new ArrayList<>();
    private static final Map<String, List<EmojiEntry>> categoryMap = new LinkedHashMap<>();

    static {
        add("😀", "Grinning Face", "Smileys", "smile", "happy", "face", "grin");
        add("😂", "Face with Tears of Joy", "Smileys", "laugh", "tears", "joy", "lol", "funny");
        add("🤣", "Rolling on Floor Laughing", "Smileys", "rofl", "laugh", "funny");
        add("😊", "Smiling Face with Smiling Eyes", "Smileys", "smile", "blush", "happy");
        add("😍", "Smiling Face with Heart-Eyes", "Smileys", "love", "heart", "crush");
        add("😘", "Face Blowing a Kiss", "Smileys", "kiss", "love");
        add("😜", "Winking Face with Tongue", "Smileys", "wink", "tongue", "silly");
        add("🤔", "Thinking Face", "Smileys", "think", "hmm", "ponder");
        add("😎", "Smiling Face with Sunglasses", "Smileys", "cool", "sunglasses");
        add("😢", "Crying Face", "Smileys", "cry", "sad", "tears");
        add("😡", "Pouting Face", "Smileys", "angry", "mad", "pout");
        add("👍", "Thumbs Up", "Gestures", "yes", "ok", "like", "approve");
        add("👎", "Thumbs Down", "Gestures", "no", "dislike", "disapprove");
        add("👏", "Clapping Hands", "Gestures", "clap", "applause", "bravo");
        add("🙏", "Folded Hands", "Gestures", "please", "thanks", "pray");
        add("💪", "Flexed Biceps", "Gestures", "strong", "muscle", "power");
        add("❤️", "Red Heart", "Hearts", "love", "heart", "like");
        add("💙", "Blue Heart", "Hearts", "blue", "heart");
        add("💚", "Green Heart", "Hearts", "green", "heart");
        add("💛", "Yellow Heart", "Hearts", "yellow", "heart");
        add("💜", "Purple Heart", "Hearts", "purple", "heart");
        add("🖤", "Black Heart", "Hearts", "black", "heart");
        add("🤍", "White Heart", "Hearts", "white", "heart");
        add("🤎", "Brown Heart", "Hearts", "brown", "heart");
        add("💔", "Broken Heart", "Hearts", "broken", "heart", "sad");
        add("🔥", "Fire", "Objects", "hot", "flame", "lit");
        add("⭐", "Star", "Objects", "star", "favorite");
        add("✨", "Sparkles", "Objects", "sparkle", "shine", "magic");
        add("🎉", "Party Popper", "Objects", "party", "celebrate", "congrats");
        add("🎂", "Birthday Cake", "Objects", "birthday", "cake", "celebrate");
        add("💰", "Money Bag", "Objects", "money", "cash", "rich");
        add("✅", "Check Mark", "Symbols", "check", "done", "complete", "yes");
        add("❌", "Cross Mark", "Symbols", "no", "wrong", "cancel", "x");
        add("⚠️", "Warning", "Symbols", "warning", "caution", "alert");
        add("ℹ️", "Information", "Symbols", "info", "information");
        add("❓", "Question Mark", "Symbols", "question", "what", "why");
        add("💯", "Hundred Points", "Symbols", "100", "perfect", "score");
        add("☕", "Hot Beverage", "Food", "coffee", "tea", "drink");
        add("🍕", "Pizza", "Food", "pizza", "food", "slice");
        add("🍔", "Hamburger", "Food", "burger", "food", "fast food");
        add("🌮", "Taco", "Food", "taco", "food", "mexican");
        add("🍩", "Doughnut", "Food", "donut", "doughnut", "sweet");
        add("🎵", "Musical Note", "Music", "music", "note", "song");
        add("🎶", "Musical Notes", "Music", "music", "notes", "song");
        add("📱", "Mobile Phone", "Tech", "phone", "mobile", "smartphone");
        add("💻", "Laptop", "Tech", "laptop", "computer", "pc");
        add("🖥️", "Desktop Computer", "Tech", "desktop", "computer", "monitor");
        add("⌨️", "Keyboard", "Tech", "keyboard", "type");
        add("🌍", "Globe Europe-Africa", "Nature", "earth", "world", "globe");
        add("🌈", "Rainbow", "Nature", "rainbow", "gay", "pride");
        add("🌸", "Cherry Blossom", "Nature", "flower", "spring", "blossom");
        add("🌙", "Crescent Moon", "Nature", "moon", "night", "crescent");
        add("☀️", "Sun", "Nature", "sun", "sunny", "day");
        add("⚡", "High Voltage", "Nature", "lightning", "electric", "zap");
        add("💧", "Droplet", "Nature", "water", "drop", "rain");
        add("🚀", "Rocket", "Travel", "rocket", "space", "launch");
        add("✈️", "Airplane", "Travel", "plane", "flight", "travel");
        add("🚗", "Automobile", "Travel", "car", "drive", "vehicle");
        add("⏰", "Alarm Clock", "Time", "alarm", "clock", "time", "wake");
        add("📅", "Calendar", "Time", "calendar", "date", "schedule");
        add("🔒", "Locked", "Objects", "lock", "secure", "private");
        add("🔑", "Key", "Objects", "key", "password", "unlock");
        add("🎯", "Bullseye", "Objects", "target", "goal", "aim");
        add("🏆", "Trophy", "Objects", "trophy", "win", "winner", "award");
        add("🎮", "Video Game", "Objects", "game", "controller", "play");
        add("📚", "Books", "Objects", "books", "read", "study", "library");
        add("✏️", "Pencil", "Objects", "pencil", "write", "draw");
        add("📝", "Memo", "Objects", "memo", "note", "write");
        add("💡", "Light Bulb", "Objects", "idea", "light", "bulb");
        add("🔔", "Bell", "Objects", "bell", "notification", "ring");
        add("🎤", "Microphone", "Objects", "mic", "sing", "karaoke");
        add("📷", "Camera", "Objects", "camera", "photo", "picture");
        add("🎬", "Clapper Board", "Objects", "movie", "film", "action");
        add("🏠", "House", "Places", "house", "home", "building");
        add("🏢", "Office Building", "Places", "office", "work", "building");
        add("🏥", "Hospital", "Places", "hospital", "doctor", "health");
        add("🏫", "School", "Places", "school", "education", "learn");
        add("⛪", "Church", "Places", "church", "religion", "worship");
        add("☮️", "Peace Symbol", "Symbols", "peace", "hippie");
        add("♻️", "Recycling Symbol", "Symbols", "recycle", "green", "environment");
        add("©️", "Copyright", "Symbols", "copyright", "c");
        add("®️", "Registered", "Symbols", "registered", "trademark", "r");
        add("™️", "Trade Mark", "Symbols", "trademark", "tm");
        add("➕", "Plus", "Symbols", "plus", "add", "math");
        add("➖", "Minus", "Symbols", "minus", "subtract", "math");
        add("✖️", "Multiply", "Symbols", "multiply", "times", "math");
        add("➗", "Divide", "Symbols", "divide", "math");
        add("〰️", "Wavy Dash", "Symbols", "wave", "dash", "squiggle");
        add("💬", "Speech Balloon", "Objects", "speech", "chat", "talk");
        add("🗨️", "Left Speech Bubble", "Objects", "chat", "talk", "reply");
        add("👋", "Waving Hand", "Gestures", "wave", "hello", "goodbye", "hi");
        add("🤝", "Handshake", "Gestures", "shake", "deal", "agree");
        add("✌️", "Victory Hand", "Gestures", "peace", "victory", "v");
        add("🤞", "Crossed Fingers", "Gestures", "luck", "hope", "fingers crossed");
        add("🤘", "Sign of the Horns", "Gestures", "rock", "metal", "horns");
        add("👌", "OK Hand", "Gestures", "ok", "perfect", "fine");
        add("🤙", "Call Me Hand", "Gestures", "call", "phone", "shaka");
        add("🖖", "Vulcan Salute", "Gestures", "spock", "star trek", "vulcan");
        add("🙂", "Slightly Smiling Face", "Smileys", "smile", "happy", "fine");
        add("🙃", "Upside-Down Face", "Smileys", "upside down", "silly", "weird");
        add("😉", "Winking Face", "Smileys", "wink", "joke", "flirt");
        add("😋", "Face Savoring Food", "Smileys", "yum", "delicious", "tasty");
        add("😛", "Face with Tongue", "Smileys", "tongue", "silly", "playful");
        add("🤪", "Zany Face", "Smileys", "crazy", "silly", "goofy");
        add("😌", "Relieved Face", "Smileys", "relieved", "calm", "peaceful");
        add("😏", "Smirking Face", "Smileys", "smirk", "smug", "flirt");
        add("😒", "Unamused Face", "Smileys", "unamused", "unimpressed", "meh");
        add("😔", "Pensive Face", "Smileys", "sad", "pensive", "sorry");
        add("😴", "Sleeping Face", "Smileys", "sleep", "tired", "zzz");
        add("🤤", "Drooling Face", "Smileys", "drool", "hungry", "want");
        add("🤢", "Nauseated Face", "Smileys", "sick", "nauseous", "gross");
        add("🤮", "Face Vomiting", "Smileys", "vomit", "sick", "throw up");
        add("🤧", "Sneezing Face", "Smileys", "sneeze", "sick", "achoo");
        add("🥵", "Hot Face", "Smileys", "hot", "sweating", "heat");
        add("🥶", "Cold Face", "Smileys", "cold", "freezing", "winter");
        add("🥳", "Partying Face", "Smileys", "party", "celebrate", "birthday");
        add("🥺", "Pleading Face", "Smileys", "please", "beg", "puppy eyes");
        add("🤯", "Exploding Head", "Smileys", "mind blown", "wow", "amazed");
        add("🤬", "Face with Symbols on Mouth", "Smileys", "swear", "curse", "angry");
        add("😈", "Smiling Face with Horns", "Smileys", "devil", "evil", "mischief");
        add("👿", "Angry Face with Horns", "Smileys", "devil", "angry", "demon");
        add("💀", "Skull", "Smileys", "skull", "death", "dead");
        add("👻", "Ghost", "Smileys", "ghost", "halloween", "spooky");
        add("👽", "Alien", "Smileys", "alien", "ufo", "space");
        add("🤖", "Robot", "Smileys", "robot", "ai", "tech");
        add("😺", "Grinning Cat", "Smileys", "cat", "smile", "happy");
        add("😸", "Grinning Cat with Smiling Eyes", "Smileys", "cat", "smile");
        add("😹", "Cat with Tears of Joy", "Smileys", "cat", "laugh", "joy");
        add("😻", "Smiling Cat with Heart-Eyes", "Smileys", "cat", "love", "heart");
        add("😼", "Cat with Wry Smile", "Smileys", "cat", "smirk");
        add("😽", "Kissing Cat", "Smileys", "cat", "kiss");
        add("🙀", "Weary Cat", "Smileys", "cat", "shocked", "surprised");
        add("😿", "Crying Cat", "Smileys", "cat", "cry", "sad");
        add("😾", "Pouting Cat", "Smileys", "cat", "angry", "pout");
        add("🐶", "Dog Face", "Animals", "dog", "puppy", "pet");
        add("🐱", "Cat Face", "Animals", "cat", "kitten", "pet");
        add("🐭", "Mouse Face", "Animals", "mouse", "rat", "rodent");
        add("🐹", "Hamster Face", "Animals", "hamster", "pet", "rodent");
        add("🐰", "Rabbit Face", "Animals", "rabbit", "bunny", "easter");
        add("🦊", "Fox Face", "Animals", "fox", "animal");
        add("🐻", "Bear Face", "Animals", "bear", "animal");
        add("🐼", "Panda Face", "Animals", "panda", "bear", "cute");
        add("🐨", "Koala", "Animals", "koala", "australia", "cute");
        add("🐯", "Tiger Face", "Animals", "tiger", "cat", "animal");
        add("🦁", "Lion Face", "Animals", "lion", "king", "animal");
        add("🐮", "Cow Face", "Animals", "cow", "moo", "farm");
        add("🐷", "Pig Face", "Animals", "pig", "oink", "farm");
        add("🐸", "Frog Face", "Animals", "frog", "toad", "amphibian");
        add("🐵", "Monkey Face", "Animals", "monkey", "ape", "animal");
        add("🐔", "Chicken", "Animals", "chicken", "bird", "farm");
        add("🐧", "Penguin", "Animals", "penguin", "bird", "cold");
        add("🐦", "Bird", "Animals", "bird", "tweet", "fly");
        add("🐤", "Baby Chick", "Animals", "chick", "bird", "easter");
        add("🦆", "Duck", "Animals", "duck", "bird", "quack");
        add("🦅", "Eagle", "Animals", "eagle", "bird", "america");
        add("🦉", "Owl", "Animals", "owl", "bird", "wise");
        add("🦇", "Bat", "Animals", "bat", "vampire", "halloween");
        add("🐺", "Wolf Face", "Animals", "wolf", "animal", "howl");
        add("🐗", "Boar", "Animals", "boar", "pig", "animal");
        add("🐴", "Horse Face", "Animals", "horse", "pony", "animal");
        add("🦄", "Unicorn Face", "Animals", "unicorn", "magic", "fantasy");
        add("🐝", "Honeybee", "Animals", "bee", "honey", "insect");
        add("🐛", "Bug", "Animals", "bug", "insect", "caterpillar");
        add("🦋", "Butterfly", "Animals", "butterfly", "insect", "beautiful");
        add("🐌", "Snail", "Animals", "snail", "slow", "insect");
        add("🐞", "Lady Beetle", "Animals", "ladybug", "insect", "bug");
        add("🐜", "Ant", "Animals", "ant", "insect", "small");
        add("🕷️", "Spider", "Animals", "spider", "insect", "web");
        add("🦂", "Scorpion", "Animals", "scorpion", "insect", "dangerous");
        add("🐢", "Turtle", "Animals", "turtle", "slow", "reptile");
        add("🐍", "Snake", "Animals", "snake", "reptile", "dangerous");
        add("🦎", "Lizard", "Animals", "lizard", "reptile");
        add("🦖", "T-Rex", "Animals", "dinosaur", "trex", "jurassic");
        add("🦕", "Sauropod", "Animals", "dinosaur", "long neck", "jurassic");
        add("🐙", "Octopus", "Animals", "octopus", "sea", "ocean");
        add("🦑", "Squid", "Animals", "squid", "sea", "ocean");
        add("🦐", "Shrimp", "Animals", "shrimp", "seafood", "ocean");
        add("🐠", "Tropical Fish", "Animals", "fish", "tropical", "ocean");
        add("🐟", "Fish", "Animals", "fish", "ocean", "sea");
        add("🐡", "Blowfish", "Animals", "blowfish", "puffer", "fish");
        add("🦈", "Shark", "Animals", "shark", "fish", "ocean");
        add("🐳", "Spouting Whale", "Animals", "whale", "ocean", "sea");
        add("🐋", "Whale", "Animals", "whale", "ocean", "sea");
        add("🐊", "Crocodile", "Animals", "crocodile", "alligator", "reptile");
        add("🐆", "Leopard", "Animals", "leopard", "cat", "animal");
        add("🐅", "Tiger", "Animals", "tiger", "cat", "animal");
        add("🐃", "Water Buffalo", "Animals", "buffalo", "cow", "farm");
        add("🐂", "Ox", "Animals", "ox", "cow", "farm");
        add("🐄", "Cow", "Animals", "cow", "moo", "farm");
        add("🐪", "Camel", "Animals", "camel", "desert", "animal");
        add("🐫", "Two-Hump Camel", "Animals", "camel", "desert", "animal");
        add("🐘", "Elephant", "Animals", "elephant", "animal", "big");
        add("🦏", "Rhinoceros", "Animals", "rhino", "animal", "big");
        add("🦍", "Gorilla", "Animals", "gorilla", "ape", "animal");
        add("🐒", "Monkey", "Animals", "monkey", "ape", "animal");
        add("🐑", "Sheep", "Animals", "sheep", "wool", "farm");
        add("🐐", "Goat", "Animals", "goat", "animal", "farm");
        add("🐏", "Ram", "Animals", "ram", "sheep", "animal");
        add("🐕", "Dog", "Animals", "dog", "puppy", "pet");
        add("🐩", "Poodle", "Animals", "poodle", "dog", "pet");
        add("🐈", "Cat", "Animals", "cat", "kitten", "pet");
        add("🐓", "Rooster", "Animals", "rooster", "chicken", "farm");
        add("🦃", "Turkey", "Animals", "turkey", "bird", "thanksgiving");
        add("🐿️", "Chipmunk", "Animals", "chipmunk", "squirrel", "animal");
        add("🐾", "Paw Prints", "Animals", "paw", "animal", "pet");
        add("🦌", "Deer", "Animals", "deer", "reindeer", "christmas");
        add("🍎", "Red Apple", "Food", "apple", "fruit", "red");
        add("🍏", "Green Apple", "Food", "apple", "fruit", "green");
        add("🍌", "Banana", "Food", "banana", "fruit");
        add("🍇", "Grapes", "Food", "grapes", "grape", "fruit");
        add("🍊", "Tangerine", "Food", "orange", "tangerine", "fruit");
        add("🍓", "Strawberry", "Food", "strawberry", "berry", "fruit");
        add("🍉", "Watermelon", "Food", "watermelon", "melon", "fruit");
        add("🍍", "Pineapple", "Food", "pineapple", "fruit");
        add("🍒", "Cherries", "Food", "cherry", "cherries", "fruit");
        add("🍑", "Peach", "Food", "peach", "fruit");
        add("🍋", "Lemon", "Food", "lemon", "citrus");
        add("🥝", "Kiwi", "Food", "kiwi", "fruit");
        add("🥑", "Avocado", "Food", "avocado", "fruit");
        add("🥕", "Carrot", "Food", "carrot", "vegetable");
        add("🍆", "Eggplant", "Food", "eggplant", "aubergine");
        add("🌽", "Corn", "Food", "corn", "maize");
        add("🥦", "Broccoli", "Food", "broccoli", "vegetable");
        add("🥒", "Cucumber", "Food", "cucumber", "pickle");
        add("🍄", "Mushroom", "Food", "mushroom", "fungus");
        add("🥔", "Potato", "Food", "potato", "vegetable");
        add("🍅", "Tomato", "Food", "tomato", "vegetable");
        add("🌶️", "Hot Pepper", "Food", "pepper", "spicy", "hot");
        add("🧄", "Garlic", "Food", "garlic");
        add("🧅", "Onion", "Food", "onion");
        add("🥥", "Coconut", "Food", "coconut", "tropical");
        add("🥭", "Mango", "Food", "mango", "fruit");
        add("🫐", "Blueberries", "Food", "blueberry", "blueberries", "berry");
        add("🍞", "Bread", "Food", "bread", "loaf");
        add("🥐", "Croissant", "Food", "croissant", "pastry");
        add("🥖", "Baguette", "Food", "baguette", "bread");
        add("🥯", "Bagel", "Food", "bagel", "bread");
        add("🧀", "Cheese", "Food", "cheese", "dairy");
        add("🥚", "Egg", "Food", "egg", "breakfast");
        add("🍳", "Cooking", "Food", "cooking", "fry", "pan");
        add("🥓", "Bacon", "Food", "bacon", "meat");
        add("🍗", "Poultry Leg", "Food", "chicken", "drumstick", "meat");
        add("🍟", "French Fries", "Food", "fries", "chips", "fast food");
        add("🌭", "Hot Dog", "Food", "hotdog", "hot dog", "sausage");
        add("🌯", "Burrito", "Food", "burrito", "wrap", "mexican");
        add("🍿", "Popcorn", "Food", "popcorn", "movie");
        add("🥨", "Pretzel", "Food", "pretzel", "snack");
        add("🥞", "Pancakes", "Food", "pancake", "pancakes", "breakfast");
        add("🧇", "Waffle", "Food", "waffle", "breakfast");
        add("🧈", "Butter", "Food", "butter", "dairy");
        add("🍦", "Ice Cream", "Food", "icecream", "soft serve", "dessert");
        add("🍧", "Shaved Ice", "Food", "shaved ice", "snow cone");
        add("🍨", "Ice Cream", "Food", "icecream", "dessert");
        add("🍰", "Shortcake", "Food", "cake", "dessert");
        add("🧁", "Cupcake", "Food", "cupcake", "cake", "dessert");
        add("🍪", "Cookie", "Food", "cookie", "biscuit", "dessert");
        add("🍬", "Candy", "Food", "candy", "sweet");
        add("🍫", "Chocolate", "Food", "chocolate", "candy", "sweet");
        add("🍭", "Lollipop", "Food", "lollipop", "candy", "sweet");
        add("🍮", "Custard", "Food", "custard", "pudding", "flan");
        add("🍯", "Honey Pot", "Food", "honey", "sweet");
        add("🍜", "Noodles", "Food", "noodles", "ramen", "soup");
        add("🍝", "Spaghetti", "Food", "spaghetti", "pasta");
        add("🍛", "Curry", "Food", "curry", "rice");
        add("🍣", "Sushi", "Food", "sushi", "japanese");
        add("🍤", "Fried Shrimp", "Food", "shrimp", "tempura");
        add("🍥", "Fish Cake", "Food", "fish cake", "naruto");
        add("🍙", "Rice Ball", "Food", "rice ball", "onigiri");
        add("🍚", "Rice", "Food", "rice");
        add("🥟", "Dumpling", "Food", "dumpling", "dumplings");
        add("🥠", "Fortune Cookie", "Food", "fortune cookie", "cookie");
        add("🥡", "Takeout Box", "Food", "takeout", "takeaway");
        add("🍱", "Bento", "Food", "bento", "lunchbox", "lunch");
        add("🥧", "Pie", "Food", "pie", "dessert");
        add("🥤", "Cup with Straw", "Food", "soda", "drink", "soft drink");
        add("🧃", "Juice Box", "Food", "juice", "drink");
        add("🥛", "Milk", "Food", "milk", "drink");
        add("🍵", "Tea", "Food", "tea", "green tea", "drink");
        add("🍺", "Beer", "Food", "beer", "drink", "alcohol");
        add("🍻", "Clinking Beer Mugs", "Food", "cheers", "beer", "toast");
        add("🍷", "Wine Glass", "Food", "wine", "drink");
        add("🍸", "Cocktail", "Food", "cocktail", "martini", "drink");
        add("🍹", "Tropical Drink", "Food", "cocktail", "drink", "tropical");
        add("🥂", "Clinking Glasses", "Food", "cheers", "toast", "celebrate");
        add("🥃", "Tumbler Glass", "Food", "whiskey", "whisky", "drink");
        add("🍾", "Bottle with Popping Cork", "Food", "champagne", "celebrate", "bottle");
        add("🍶", "Sake", "Food", "sake", "rice wine");
        add("🍲", "Pot of Food", "Food", "stew", "soup", "pot");
        add("🥘", "Shallow Pan of Food", "Food", "paella", "pan");
        add("🥗", "Green Salad", "Food", "salad", "healthy");
        add("🥙", "Stuffed Flatbread", "Food", "kebab", "gyro", "wrap");
        add("🧆", "Falafel", "Food", "falafel");
        add("🍠", "Roasted Sweet Potato", "Food", "sweet potato", "yam");
        add("🥜", "Peanuts", "Food", "peanut", "peanuts", "nuts");
        add("🫒", "Olive", "Food", "olive", "oil");
        add("🫘", "Beans", "Food", "bean", "beans", "legume");
        add("🥢", "Chopsticks", "Food", "chopsticks", "asian");
        add("🍽️", "Fork and Knife with Plate", "Food", "dining", "food", "dinner");
        add("🍴", "Fork and Knife", "Food", "fork", "knife", "cutlery");
        add("🥄", "Spoon", "Food", "spoon", "cutlery");
        add("🔪", "Kitchen Knife", "Food", "knife", "cut", "chef");
        add("🏺", "Amphora", "Food", "amphora", "vase", "pottery");
        add("🧂", "Salt", "Food", "salt", "seasoning");
        add("🍼", "Baby Bottle", "Food", "baby", "milk", "bottle");
        add("🫖", "Teapot", "Food", "teapot", "tea");
        add("🧉", "Mate", "Food", "mate", "tea");
        add("🫗", "Pouring Liquid", "Food", "pour", "drink");
        add("🌦️", "Sun Behind Rain Cloud", "Nature", "weather", "rain", "sun");
        add("🌧️", "Cloud with Rain", "Nature", "rain", "weather");
        add("⛈️", "Cloud with Lightning and Rain", "Nature", "storm", "thunder", "lightning");
        add("🌩️", "Cloud with Lightning", "Nature", "lightning", "storm");
        add("🌨️", "Cloud with Snow", "Nature", "snow", "weather");
        add("❄️", "Snowflake", "Nature", "snow", "flake", "cold", "winter");
        add("☃️", "Snowman", "Nature", "snowman", "snow", "winter");
        add("⛄", "Snowman Without Snow", "Nature", "snowman", "snow");
        add("🌬️", "Wind Face", "Nature", "wind", "blow");
        add("🌀", "Cyclone", "Nature", "cyclone", "hurricane", "tornado");
        add("🌫️", "Foggy", "Nature", "fog", "mist");
        add("🌪️", "Tornado", "Nature", "tornado", "cyclone");
        add("🌡️", "Thermometer", "Nature", "thermometer", "temperature", "fever", "heat");
        add("🧊", "Ice", "Nature", "ice", "cube", "cold");
        add("🪨", "Rock", "Nature", "rock", "stone");
        add("🦴", "Bone", "Nature", "bone", "skeleton");
        add("🧠", "Brain", "Nature", "brain", "mind", "intelligence");
        add("🫀", "Anatomical Heart", "Nature", "anatomical", "heart", "organ");
        add("🫁", "Lungs", "Nature", "lung", "lungs", "breathe");
        add("👁️", "Eye", "Nature", "eye", "sight");
        add("👀", "Eyes", "Nature", "eyes", "look", "watch");
        add("👄", "Lips", "Nature", "lips", "mouth", "kiss");
        add("🦷", "Tooth", "Nature", "tooth", "teeth", "dental");
        add("🦵", "Leg", "Nature", "leg", "limb");
        add("🦶", "Foot", "Nature", "foot", "feet");
        add("💅", "Nail Polish", "Nature", "nails", "nail polish", "manicure");
        add("🦠", "Microbe", "Nature", "bacteria", "germ", "virus");
        add("🌻", "Sunflower", "Nature", "sunflower", "flower");
        add("🌷", "Tulip", "Nature", "tulip", "flower");
        add("🌹", "Rose", "Nature", "rose", "flower", "love");
        add("🌺", "Hibiscus", "Nature", "hibiscus", "flower");
        add("🌴", "Palm Tree", "Nature", "palm", "tree", "tropical");
        add("🌳", "Tree", "Nature", "tree", "forest");
        add("🌲", "Evergreen Tree", "Nature", "tree", "pine", "forest");
        add("🍀", "Four Leaf Clover", "Nature", "clover", "luck", "lucky");
        add("🍃", "Leaf", "Nature", "leaf", "leaves", "autumn");
        add("🍂", "Fallen Leaf", "Nature", "leaf", "autumn", "fall");
        add("🍁", "Maple Leaf", "Nature", "maple", "leaf", "autumn", "canada");
        add("🐚", "Spiral Shell", "Nature", "shell", "beach", "seashell");
        add("🌊", "Ocean Wave", "Nature", "wave", "ocean", "sea", "water");
        add("🌋", "Volcano", "Nature", "volcano", "eruption");
        add("⛰️", "Mountain", "Nature", "mountain");
        add("🏔️", "Snow-Capped Mountain", "Nature", "mountain", "snow");
        add("🗻", "Mount Fuji", "Nature", "mountain", "fuji");
        add("🏜️", "Desert", "Nature", "desert", "sand");
        add("🏝️", "Desert Island", "Nature", "island", "tropical");
        add("🏞️", "National Park", "Nature", "park", "nature");
        add("🗺️", "World Map", "Nature", "map", "world", "globe");
        add("🌏", "Globe Asia-Australia", "Nature", "earth", "globe", "world");
        add("🌎", "Globe Americas", "Nature", "earth", "globe", "world");
        add("🌕", "Full Moon", "Nature", "moon", "full moon", "night");
        add("🌖", "Waning Gibbous Moon", "Nature", "moon");
        add("🌗", "Last Quarter Moon", "Nature", "moon");
        add("🌘", "Waning Crescent Moon", "Nature", "moon");
        add("🌑", "New Moon", "Nature", "moon");
        add("🌒", "Waxing Crescent Moon", "Nature", "moon");
        add("🌓", "First Quarter Moon", "Nature", "moon");
        add("🌔", "Waxing Gibbous Moon", "Nature", "moon");
        add("🌝", "Full Moon Face", "Nature", "moon", "face");
        add("🌛", "First Quarter Moon Face", "Nature", "moon");
        add("🌜", "Last Quarter Moon Face", "Nature", "moon");
        add("🌚", "New Moon Face", "Nature", "moon", "dark");
        add("🌟", "Glowing Star", "Nature", "star", "glow", "shine");
        add("💫", "Dizzy", "Nature", "dizzy", "star", "sparkle");
        add("🌠", "Shooting Star", "Nature", "shooting star", "star", "wish");
        add("🌌", "Milky Way", "Nature", "galaxy", "milky way", "space");
        add("🌆", "Cityscape at Dusk", "Places", "city", "dusk", "evening");
        add("🌃", "Night with Stars", "Places", "night", "city", "stars");
        add("🌇", "Sunset", "Places", "sunset", "evening");
        add("🌅", "Sunrise", "Places", "sunrise", "morning", "dawn");
        add("🌄", "Sunrise over Mountains", "Places", "sunrise", "mountains");
        add("🏰", "Castle", "Places", "castle");
        add("🏯", "Japanese Castle", "Places", "castle", "japanese");
        add("🗼", "Tokyo Tower", "Places", "tokyo", "tower");
        add("🗽", "Statue of Liberty", "Places", "liberty", "statue", "new york");
        add("⛲", "Fountain", "Places", "fountain", "water");
        add("🎡", "Ferris Wheel", "Places", "ferris wheel", "fair", "wheel");
        add("🎢", "Roller Coaster", "Places", "rollercoaster", "coaster", "amusement");
        add("🎠", "Carousel Horse", "Places", "carousel", "merry go round");
        add("🗿", "Moai", "Places", "moai", "statue", "stone");
        add("🏖️", "Beach with Umbrella", "Places", "beach", "sand");
        add("🏗️", "Building Construction", "Places", "construction", "building", "build");
        add("🏘️", "Houses", "Places", "houses", "homes");
        add("🏙️", "Cityscape", "Places", "city", "skyline");
        add("🏪", "Convenience Store", "Places", "store", "shop", "convenience");
        add("🏬", "Department Store", "Places", "store", "department");
        add("🏨", "Hotel", "Places", "hotel");
        add("🏭", "Factory", "Places", "factory", "industrial");
        add("🕌", "Mosque", "Places", "mosque", "muslim");
        add("🕍", "Synagogue", "Places", "synagogue", "jewish");
        add("🛕", "Hindu Temple", "Places", "temple", "hindu");
        add("⛩️", "Shrine", "Places", "shrine", "shinto");
        add("🛤️", "Railway Track", "Places", "railway", "track", "train");
        add("🛣️", "Highway", "Places", "highway", "road", "motorway");
        add("🛢️", "Oil Drum", "Places", "oil", "barrel", "drum");
        add("🗾", "Map of Japan", "Places", "japan", "map");
        add("⚽", "Soccer Ball", "Objects", "football", "soccer", "ball", "sport");
        add("🏀", "Basketball", "Objects", "basketball", "ball", "sport");
        add("🏈", "American Football", "Objects", "football", "nfl", "sport");
        add("⚾", "Baseball", "Objects", "baseball", "ball", "sport");
        add("🎾", "Tennis", "Objects", "tennis", "ball", "sport");
        add("🎱", "Pool 8 Ball", "Objects", "pool", "billiards", "8ball", "ball");
        add("🏉", "Rugby", "Objects", "rugby", "ball", "sport");
        add("🥅", "Goal Net", "Objects", "goal", "net", "score");
        add("🏐", "Volleyball", "Objects", "volleyball", "ball", "sport");
        add("🏓", "Ping Pong", "Objects", "pingpong", "table tennis", "paddle");
        add("🏸", "Badminton", "Objects", "badminton", "shuttlecock", "sport");
        add("🥊", "Boxing Glove", "Objects", "boxing", "glove", "box");
        add("🥋", "Martial Arts", "Objects", "martial arts", "karate", "judo");
        add("🥌", "Curling Stone", "Objects", "curling", "stone");
        add("⛳", "Flag in Hole", "Objects", "golf", "flag", "hole");
        add("🏌️", "Golfer", "Objects", "golf", "golfer", "swing");
        add("🏄", "Surfer", "Objects", "surf", "surfer", "surfing");
        add("🏊", "Swimmer", "Objects", "swim", "swimmer", "swimming");
        add("🤽", "Water Polo", "Objects", "water polo", "swim");
        add("🚣", "Rowing Boat", "Objects", "row", "rowing", "boat");
        add("🧗", "Climbing Person", "Objects", "climb", "climbing", "rock");
        add("🚴", "Bicyclist", "Objects", "cycle", "cycling", "bike");
        add("🚵", "Mountain Bicyclist", "Objects", "bike", "cycling", "mountain bike");
        add("🏇", "Horse Racing", "Objects", "horse", "racing", "race");
        add("⛷️", "Skier", "Objects", "ski", "skier", "skiing");
        add("🎿", "Skis", "Objects", "ski", "skiing", "snow");
        add("🏂", "Snowboarder", "Objects", "snowboard", "snowboarding");
        add("🏋️", "Weight Lifter", "Objects", "weight", "lift", "gym", "muscle");
        add("🤸", "Cartwheeling", "Objects", "cartwheel", "gymnastics", "flip");
        add("🤺", "Person Fencing", "Objects", "fencing", "fence", "sword");
        add("🤼", "Wrestlers", "Objects", "wrestling", "wrestle");
        add("🤾", "Handball", "Objects", "handball");
        add("🤹", "Juggler", "Objects", "juggle", "juggling");
        add("🧘", "Lotus Position", "Objects", "yoga", "meditate", "meditation", "lotus");
        add("🛀", "Person Taking Bath", "Objects", "bath", "bathing", "bathtub");
        add("🛌", "Person in Bed", "Objects", "sleep", "bed", "sleeping");
        add("🏃", "Runner", "Objects", "run", "runner", "running", "sprint");
        add("🚶", "Pedestrian", "Objects", "walk", "walking", "pedestrian");
        add("💃", "Dancer", "Objects", "dance", "dancer", "dancing");
        add("🕺", "Man Dancing", "Objects", "dance", "dancing");
        add("🏕️", "Camping", "Objects", "camp", "camping", "tent");
        add("⛺", "Tent", "Objects", "tent", "camp", "camping");
        add("🏹", "Bow and Arrow", "Objects", "bow", "arrow", "archery");
        add("🎣", "Fishing Pole", "Objects", "fishing", "fish", "rod");
        add("🎪", "Circus Tent", "Objects", "circus");
        add("🎭", "Performing Arts", "Objects", "theater", "theatre", "drama", "mask");
        add("🎨", "Artist Palette", "Objects", "artist", "paint", "palette", "art");
        add("🕹️", "Joystick", "Objects", "joystick", "game");
        add("🎲", "Game Die", "Objects", "dice", "die", "game", "luck");
        add("🧩", "Puzzle Piece", "Objects", "puzzle", "jigsaw");
        add("♟️", "Chess Pawn", "Objects", "chess");
        add("🎰", "Slot Machine", "Objects", "slot", "casino", "gamble");
        add("🀄", "Mahjong", "Objects", "mahjong");
        add("🎴", "Flower Cards", "Objects", "cards", "hanafuda");
        add("🃏", "Joker", "Objects", "joker", "card", "cards");
        add("🎳", "Bowling", "Objects", "bowling", "bowl", "pins");
        add("🎁", "Wrapped Gift", "Objects", "gift", "present", "birthday");
        add("🎈", "Balloon", "Objects", "balloon", "party");
        add("🎀", "Ribbon", "Objects", "ribbon", "bow");
        add("🧸", "Teddy Bear", "Objects", "teddy", "teddy bear", "bear", "toy");
        add("🎄", "Christmas Tree", "Objects", "christmas", "xmas", "tree");
        add("🎅", "Santa Claus", "Objects", "santa", "christmas", "claus");
        add("🧑‍🎄", "Mx Claus", "Objects", "santa", "christmas");
        add("🎊", "Confetti Ball", "Objects", "confetti", "party", "celebrate");
        add("🎆", "Fireworks", "Objects", "firework", "fireworks", "celebrate");
        add("🎇", "Sparkler", "Objects", "sparkler", "firework");
        add("🪅", "Piñata", "Objects", "pinata", "party");
        add("🪩", "Mirror Ball", "Objects", "disco", "dance", "party");
        add("🪆", "Nesting Dolls", "Objects", "nesting dolls", "matryoshka");
        add("💍", "Ring", "Objects", "ring", "engagement", "wedding", "propose");
        add("💎", "Gem Stone", "Objects", "gem", "diamond", "jewel", "jewellery");
        add("🪙", "Coin", "Objects", "coin", "money");
        add("💵", "Dollar Banknote", "Objects", "dollar", "money", "cash", "banknote");
        add("💴", "Yen Banknote", "Objects", "yen", "money");
        add("💶", "Euro Banknote", "Objects", "euro", "money");
        add("💷", "Pound Banknote", "Objects", "pound", "money");
        add("💸", "Money with Wings", "Objects", "money", "spend", "cash");
        add("💳", "Credit Card", "Objects", "card", "credit", "payment", "bank");
        add("🧾", "Receipt", "Objects", "receipt", "bill");
        add("💲", "Heavy Dollar Sign", "Objects", "dollar", "money");
        add("💱", "Currency Exchange", "Objects", "exchange", "currency");
        add("🪪", "ID Card", "Objects", "id", "card", "badge");
        add("🗑️", "Wastebasket", "Objects", "trash", "bin", "rubbish", "delete");
        add("🛒", "Shopping Cart", "Objects", "shopping", "cart", "trolley");
        add("🛍️", "Shopping Bags", "Objects", "shopping", "bags");
        add("🔋", "Battery", "Objects", "battery", "power", "charge", "energy");
        add("🔌", "Electric Plug", "Objects", "plug", "power", "electric");
        add("🔦", "Flashlight", "Objects", "torch", "flashlight", "light");
        add("🕯️", "Candle", "Objects", "candle", "light");
        add("🔧", "Wrench", "Objects", "wrench", "tool", "fix", "spanner");
        add("🔨", "Hammer", "Objects", "hammer", "tool", "fix");
        add("🛠️", "Hammer and Wrench", "Objects", "tool", "tools", "fix", "repair");
        add("⚒️", "Hammer and Pick", "Objects", "hammer", "pick", "mining");
        add("⛏️", "Pick", "Objects", "pick", "mining", "tool");
        add("🔩", "Nut and Bolt", "Objects", "bolt", "screw", "nut");
        add("⚙️", "Gear", "Objects", "gear", "settings", "mechanical", "cog");
        add("🛰️", "Satellite", "Objects", "satellite", "space", "orbit");
        add("🔭", "Telescope", "Objects", "telescope", "space", "astronomy", "stars");
        add("🔬", "Microscope", "Objects", "microscope", "science", "lab");
        add("🧪", "Test Tube", "Objects", "test tube", "science", "lab", "chemistry");
        add("🧫", "Petri Dish", "Objects", "petri dish", "science", "lab", "bacteria");
        add("🧬", "DNA", "Objects", "dna", "gene", "genetics", "science");
        add("⚗️", "Alembic", "Objects", "alembic", "chemistry", "distill");
        add("🧲", "Magnet", "Objects", "magnet", "attract", "magnets");
        add("🧯", "Fire Extinguisher", "Objects", "fire", "extinguisher", "safety");
        add("🪜", "Ladder", "Objects", "ladder", "climb");
        add("🧰", "Toolbox", "Objects", "toolbox", "tools", "tool");
        add("🪛", "Screwdriver", "Objects", "screwdriver", "tool");
        add("🔫", "Water Pistol", "Objects", "gun", "pistol", "toy");
        add("🧹", "Broom", "Objects", "broom", "clean", "sweep");
        add("🧺", "Basket", "Objects", "basket", "picnic");
        add("🧶", "Yarn", "Objects", "yarn", "knit", "wool");
        add("🧵", "Thread", "Objects", "thread", "sew");
        add("🪡", "Sewing Needle", "Objects", "needle", "sew");
        add("🪢", "Knot", "Objects", "knot", "tie");
        add("🩹", "Bandage", "Objects", "bandage", "plaster", "wound");
        add("🩺", "Stethoscope", "Objects", "stethoscope", "doctor", "medical");
        add("🩻", "X-Ray", "Objects", "xray", "x-ray", "scan");
        add("🩼", "Crutch", "Objects", "crutch", "injury");
        add("🛡️", "Shield", "Objects", "shield", "protect", "defense");
        add("⚔️", "Crossed Swords", "Objects", "swords", "sword", "fight");
        add("🗡️", "Dagger", "Objects", "dagger", "knife");
        add("🧿", "Nazar Amulet", "Objects", "nazar", "evil eye", "protection");
        add("🪬", "Hand of Fatima", "Objects", "hamsa", "protection");
        add("🔮", "Crystal Ball", "Objects", "crystal ball", "fortune", "magic", "psychic");
        add("🪄", "Magic Wand", "Objects", "magic", "wand");
        add("🕳️", "Hole", "Objects", "hole");
        add("🕸️", "Spider Web", "Objects", "web", "spider");
        add("🎗️", "Reminder Ribbon", "Objects", "ribbon", "awareness");
        add("🎟️", "Admission Tickets", "Objects", "ticket", "tickets");
        add("🎫", "Ticket", "Objects", "ticket");
        add("🎖️", "Military Medal", "Objects", "medal", "award");
        add("🏅", "Sports Medal", "Objects", "medal", "gold", "win");
        add("🥇", "Gold Medal", "Objects", "gold", "medal", "winner", "win");
        add("🥈", "Silver Medal", "Objects", "silver", "medal", "second");
        add("🥉", "Bronze Medal", "Objects", "bronze", "medal", "third");
        add("🏁", "Checkered Flag", "Objects", "checkered", "racing", "finish");
        add("🎌", "Crossed Flags", "Objects", "flags", "japan");
        add("🏴", "Black Flag", "Objects", "flag", "black");
        add("🏳️", "White Flag", "Objects", "flag", "white", "surrender");
        add("🏳️‍🌈", "Rainbow Flag", "Objects", "pride", "rainbow", "lgbt");
        add("🏴‍☠️", "Pirate Flag", "Objects", "pirate", "flag");
        add("🚩", "Triangular Flag", "Objects", "flag");
        add("🚒", "Fire Engine", "Objects", "fire engine", "firetruck", "fire", "truck");
        add("🚓", "Police Car", "Objects", "police", "car");
        add("🚑", "Ambulance", "Objects", "ambulance", "medical", "emergency");
        add("🚌", "Bus", "Objects", "bus");
        add("🚐", "Minibus", "Objects", "bus", "minibus");
        add("🚕", "Taxi", "Objects", "taxi", "cab");
        add("🚙", "Sport Utility Vehicle", "Objects", "suv", "car", "offroad");
        add("🚚", "Delivery Truck", "Objects", "truck", "delivery", "lorry");
        add("🚛", "Articulated Lorry", "Objects", "truck", "lorry", "semi");
        add("🚜", "Tractor", "Objects", "tractor", "farm");
        add("🚲", "Bicycle", "Objects", "bike", "bicycle", "cycle");
        add("🛵", "Motor Scooter", "Objects", "scooter", "vespa");
        add("🏍️", "Motorcycle", "Objects", "motorcycle", "motorbike", "bike");
        add("🛴", "Kick Scooter", "Objects", "scooter");
        add("🚄", "High-Speed Train", "Objects", "train", "bullet train", "shinkansen");
        add("🚅", "Bullet Train", "Objects", "bullet", "train", "shinkansen");
        add("🚆", "Train", "Objects", "train");
        add("🚇", "Metro", "Objects", "metro", "subway", "underground");
        add("🚈", "Light Rail", "Objects", "train", "rail");
        add("🚉", "Station", "Objects", "station", "train");
        add("🚊", "Tram", "Objects", "tram");
        add("🚝", "Monorail", "Objects", "monorail", "train");
        add("🚞", "Mountain Railway", "Objects", "railway", "mountain", "train");
        add("🚋", "Tram Car", "Objects", "tram", "car");
        add("🚃", "Railway Car", "Objects", "railway", "car", "train");
        add("🚂", "Locomotive", "Objects", "train", "locomotive", "steam");
        add("🚁", "Helicopter", "Objects", "helicopter", "chopper");
        add("🛸", "Flying Saucer", "Objects", "ufo", "saucer", "alien", "space");
        add("🛩️", "Small Airplane", "Objects", "plane", "airplane", "flight");
        add("🛫", "Airplane Departure", "Objects", "departure", "takeoff", "flight");
        add("🛬", "Airplane Arrival", "Objects", "arrival", "landing", "flight");
        add("🚢", "Ship", "Objects", "ship", "boat", "cruise");
        add("⛵", "Sailboat", "Objects", "sailboat", "boat", "sail");
        add("🚤", "Speedboat", "Objects", "speedboat", "boat");
        add("🛥️", "Motorboat", "Objects", "boat", "motorboat");
        add("⛴️", "Ferry", "Objects", "ferry", "boat");
        add("⚓", "Anchor", "Objects", "anchor", "ship", "sail");
        add("🚧", "Construction", "Objects", "construction", "roadwork", "barrier");
        add("🚦", "Traffic Light", "Objects", "traffic", "light", "traffic light");
        add("🚥", "Vertical Traffic Light", "Objects", "traffic", "light");
        add("🛑", "Stop Sign", "Objects", "stop", "stop sign");
        add("🚨", "Police Car Light", "Objects", "siren", "police", "alert");
        add("⛽", "Fuel Pump", "Objects", "fuel", "gas", "petrol", "pump");
        add("🚏", "Bus Stop", "Objects", "bus stop", "bus", "stop");
        add("🖨️", "Printer", "Tech", "printer", "print");
        add("🖱️", "Computer Mouse", "Tech", "mouse", "computer");
        add("🖲️", "Trackball", "Tech", "trackball", "mouse");
        add("💾", "Floppy Disk", "Tech", "floppy", "save", "disk");
        add("💿", "Optical Disk", "Tech", "cd", "disc", "disk");
        add("📀", "DVD", "Tech", "dvd", "disc");
        add("📼", "Videocassette", "Tech", "vhs", "tape", "cassette");
        add("📸", "Camera with Flash", "Tech", "camera", "flash", "photo");
        add("📹", "Video Camera", "Tech", "video", "camcorder", "camera");
        add("🎥", "Movie Camera", "Tech", "movie", "film", "camera", "cinema");
        add("📽️", "Film Projector", "Tech", "projector", "film", "movie");
        add("🎞️", "Film Frames", "Tech", "film", "frames");
        add("📞", "Telephone Receiver", "Tech", "telephone", "phone", "call");
        add("☎️", "Telephone", "Tech", "telephone", "phone", "call");
        add("📟", "Pager", "Tech", "pager", "beeper");
        add("📠", "Fax Machine", "Tech", "fax", "fax machine");
        add("📻", "Radio", "Tech", "radio");
        add("🎙️", "Studio Microphone", "Tech", "mic", "microphone", "studio");
        add("🎚️", "Level Slider", "Tech", "slider", "volume");
        add("🎛️", "Control Knobs", "Tech", "knobs", "volume", "controls");
        add("📡", "Satellite Antenna", "Tech", "satellite", "signal", "antenna");
        add("⌚", "Watch", "Tech", "watch", "time");
        add("📲", "Mobile Phone with Arrow", "Tech", "phone", "mobile", "receive");
        add("📶", "Antenna Bars", "Tech", "signal", "bars", "wifi");
        add("📳", "Vibration Mode", "Tech", "vibrate", "phone");
        add("📴", "Mobile Phone Off", "Tech", "off", "phone");
        add("💽", "Computer Disk", "Tech", "disk", "disc");
        add("🕐", "One O'Clock", "Time", "time", "clock", "one");
        add("🕑", "Two O'Clock", "Time", "time", "clock", "two");
        add("🕒", "Three O'Clock", "Time", "time", "clock", "three");
        add("🕓", "Four O'Clock", "Time", "time", "clock", "four");
        add("🕔", "Five O'Clock", "Time", "time", "clock", "five");
        add("🕕", "Six O'Clock", "Time", "time", "clock", "six");
        add("🕖", "Seven O'Clock", "Time", "time", "clock", "seven");
        add("🕗", "Eight O'Clock", "Time", "time", "clock", "eight");
        add("🕘", "Nine O'Clock", "Time", "time", "clock", "nine");
        add("🕙", "Ten O'Clock", "Time", "time", "clock", "ten");
        add("🕚", "Eleven O'Clock", "Time", "time", "clock", "eleven");
        add("🕛", "Twelve O'Clock", "Time", "time", "clock", "twelve");
        add("🕧", "Twelve-Thirty", "Time", "time", "clock", "half past");
        add("⏱️", "Stopwatch", "Time", "stopwatch", "timer");
        add("⏲️", "Timer Clock", "Time", "timer", "countdown");
        add("🕰️", "Mantelpiece Clock", "Time", "clock", "mantelpiece");
        add("⌛", "Hourglass", "Time", "hourglass", "time", "wait");
        add("⏳", "Hourglass with Flowing Sand", "Time", "hourglass", "time", "wait");
        add("📆", "Tear-Off Calendar", "Time", "calendar", "date");
        add("🗓️", "Spiral Calendar", "Time", "calendar", "date");
        add("📇", "Card Index", "Time", "contacts", "rolodex");
        add("🗒️", "Spiral Notepad", "Time", "notepad", "notes", "note");
    }

    private static void add(String emoji, String name, String category, String... keywords) {
        EmojiEntry entry = new EmojiEntry(emoji, name, category, keywords);
        emojis.add(entry);
        categoryMap.computeIfAbsent(category, k -> new ArrayList<>()).add(entry);
    }

    public static List<EmojiEntry> getAllEmojis() { return emojis; }

    public static Map<String, List<EmojiEntry>> getCategoryMap() { return categoryMap; }

    public static List<EmojiEntry> search(String query) {
        List<EmojiEntry> results = new ArrayList<>();
        String q = query.toLowerCase().trim();
        if (q.isEmpty()) return results;
        for (EmojiEntry e : emojis) {
            if (e.name.toLowerCase().contains(q)) { results.add(e); continue; }
            for (String kw : e.keywords) {
                if (kw.contains(q)) { results.add(e); break; }
            }
        }
        return results;
    }

    public static List<EmojiEntry> getEmojiForWord(String word) {
        List<EmojiEntry> results = new ArrayList<>();
        if (word == null) return results;
        String w = word.trim().toLowerCase();
        if (w.isEmpty()) return results;
        for (EmojiEntry e : emojis) {
            if (matchesWord(e, w)) {
                if (!results.contains(e)) results.add(e);
            }
        }
        if (results.isEmpty() && w.length() > 1 && w.endsWith("s")) {
            String singular = w.substring(0, w.length() - 1);
            for (EmojiEntry e : emojis) {
                if (matchesWord(e, singular)) {
                    if (!results.contains(e)) results.add(e);
                }
            }
        }
        if (results.size() > 4) return results.subList(0, 4);
        return results;
    }

    private static boolean matchesWord(EmojiEntry e, String word) {
        if (e.name.toLowerCase().equals(word)) return true;
        for (String kw : e.keywords) {
            if (kw.equals(word)) return true;
        }
        return false;
    }
}
